Fix not being able to open NuGet package from dialog
Opening a NuGet package from the dialog would not open a tab. The
problem was that the view is pre-created and was not setting a
DocumentTitle early enough causing VS Mac 17.3 Preview 3 to
throw an ArgumentNullException trying to set the tab's label to null.

Async operation failed
System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'value'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at ObjCRuntime.ThrowHelper.ThrowArgumentNullException(String argumentName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/ThrowHelper.cs:line 28
   at AppKit.NSControl.set_StringValue(String value) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/build/dotnet/macos/generated-sources/AppKit/NSControl.g.cs:line 1433
   at VisualStudioMac.UI.TabStrip.TabView.UpdateLabel() in /Users/runner/work/1/s/main/src/core/VisualStudio/UI/TabStrip/TabView.cs:line 576
   at VisualStudioMac.UI.TabStrip.TabView.UpdateProperties() in /Users/runner/work/1/s/main/src/core/VisualStudio/UI/TabStrip/TabView.cs:line 669
   at VisualStudioMac.UI.TabStrip.TabView.ViewDidMoveToSuperview() in /Users/runner/work/1/s/main/src/core/VisualStudio/UI/TabStrip/TabView.cs:line 683
   at VisualStudioMac.UI.TabStrip.ShellTabView.ViewDidMoveToSuperview() in /Users/runner/work/1/s/main/src/core/VisualStudio/UI/TabStrip/TabView.cs:line 236
--- End of stack trace from previous location ---
   at ObjCRuntime.Runtime.InvokeMethod(MethodBase method, Object instance, IntPtr native_parameters) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Runtime.CoreCLR.cs:line 657
   at ObjCRuntime.Runtime.InvokeMethod(MonoObject* methodobj, MonoObject* instanceobj, IntPtr native_parameters) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Runtime.CoreCLR.cs:line 552
   at ObjCRuntime.Runtime.bridge_runtime_invoke_method(MonoObject* method, MonoObject* instance, IntPtr parameters, IntPtr& exception_gchandle) in /Users/builder/azdo/_work/1/s/xamarin-macios/runtime/Delegates.generated.cs:line 1216
   at ObjCRuntime.Messaging.void_objc_msgSendSuper_NativeHandle(IntPtr receiver, IntPtr selector, NativeHandle arg1)
   at AppKit.NSStackView.AddArrangedSubview(NSView view) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/build/dotnet/macos/generated-sources/AppKit/NSStackView.g.cs:line 230
   at VisualStudioMac.UI.TabStrip.CocoaTabStripView.TabAdded(INotebookTab tab) in /Users/runner/work/1/s/main/src/core/VisualStudio/UI/TabStrip/CocoaTabStripView.cs:line 269
   at MonoDevelop.Components.TabStrip.TabStripController.AddTab(INotebookTab tab) in /Users/runner/work/1/s/main/src/core/MonoDevelop.Ide/MonoDevelop.Components.TabStrip/TabStripController.cs:line 64
   at MonoDevelop.Components.TabStrip.TabStripController.InsertTab(INotebookTab tab, Int32 position) in /Users/runner/work/1/s/main/src/core/MonoDevelop.Ide/MonoDevelop.Components.TabStrip/TabStripController.cs:line 71
   at MonoDevelop.Components.TabStrip.PinnableTabStripController.InsertTab(IShellNotebookTab tab, Int32 index) in /Users/runner/work/1/s/main/src/core/MonoDevelop.Ide/MonoDevelop.Components.TabStrip/PinnableTabStripController.cs:line 90
   at MonoDevelop.Components.DockNotebook.DockNotebookController.InsertTab(IShellNotebookTab tab, Int32 index) in /Users/runner/work/1/s/main/src/core/MonoDevelop.Ide/MonoDevelop.Components.DockNotebook/DockNotebookController.cs:line 390
   at MonoDevelop.Components.DockNotebook.DockNotebookController.InsertTab(Int32 index, IShellNotebookTabContent content) in /Users/runner/work/1/s/main/src/core/MonoDevelop.Ide/MonoDevelop.Components.DockNotebook/DockNotebookController.cs:line 379
   at MonoDevelop.Components.DockNotebook.DockNotebookController.AddTab(IShellNotebookTabContent content) in /Users/runner/work/1/s/main/src/core/MonoDevelop.Ide/MonoDevelop.Components.DockNotebook/DockNotebookController.cs:line 361
   at VisualStudioMac.CocoaShellViewController.ShowViewAsync(DocumentController controller, IShellNotebook notebook, Object viewCommandHandler) in /Users/runner/work/1/s/main/src/core/VisualStudio/Application/Shell/CocoaShellViewController.cs:line 325
   at VisualStudioMac.CocoaWorkbenchController.MonoDevelop.Ide.Gui.Shell.IShell.ShowView(DocumentController controller, IShellNotebook notebook, Object viewCommandHandler) in /Users/runner/work/1/s/main/src/core/VisualStudio/Application/Shell/CocoaWorkbenchController.cs:line 247
   at MonoDevelop.Ide.Gui.Documents.DocumentManager.ShowView(DocumentOpenInformation documentOpenInfo) in /Users/runner/work/1/s/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentManager.cs:line 664
   at MonoDevelop.Ide.Gui.Documents.DocumentManager.OpenDocument(DocumentController controller, Boolean bringToFront) in /Users/runner/work/1/s/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentManager.cs:line 289