Fix package list not displaying properly
The package list was squashed into a small square at the top left
corner due to an invalid cast exception:

System.InvalidCastException: Specified cast is not valid.
  at MonoDevelop.PackageManagement.PackageCellView.CreateCheckboxImages ()
  in MonoDevelop.PackageManagement.Gui/PackageCellView.cs:184