Fix null reference when opening new file dialog
Opening the new file dialog would pass a null FilePath to the
NuGetPackageDisplayBinding's CanHandle method causing an exception.

Error while getting display bindings
System.NullReferenceException: Object reference not set to an instance of an object
  at MonoDevelop.Core.FilePath.HasExtension (System.String extension) [0x00001] in monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Core/FilePath.cs:155
  at MonoDevelop.NuGetPackageExplorer.NuGetPackageDisplayBinding.CanHandle (MonoDevelop.Core.FilePath fileName, System.String mimeType, MonoDevelop.Projects.Project ownerProject) [0x00001] in <d84baf327fd745198d545aae87b13312>:0
  at MonoDevelop.Ide.Gui.DisplayBindingService+<GetDisplayBindings>d__4.MoveNext () [0x00093] in monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/DisplayBindingService.cs:68

Fixes #1