Update addin version to 0.9 and target VS Mac 17.3
VS Mac 17.3 has an API break for the Ide.Styles - which requires
rebuilding against the newer assembly.

System.MissingMethodException: Method not found: 'Xwt.Drawing.Color
MonoDevelop.Ide.Gui.Styles.get_ErrorForegroundColor()'.
   at MonoDevelop.PackageManagement.Styles.LoadStyles()
   at MonoDevelop.PackageManagement.Styles..cctor()
   --- End of inner exception stack trace ---
   at MonoDevelop.PackageManagement.Styles.get_LineBorderColor()
   at MonoDevelop.PackageManagement.AddPackagesDialog.Build()
   at MonoDevelop.PackageManagement.AddPackagesDialog..ctor(
AllPackagesViewModel viewModel, String initialSearch)
   at MonoDevelop.NuGetPackageExplorer
.OpenNuGetPackageFromSourceHandler.CreateDialog(String initialSearch)
   at MonoDevelop.NuGetPackageExplorer
.OpenNuGetPackageFromSourceHandler.Run(String initialSearch)