Update to NuGet 5.2.0
Update to NuGet 5.2.0 from NuGet 4.8.0. Later versions support
the new license metadata information in the .nuspec.

Updated ILRepack to 2.0.17

Had to point ILRepack to the location of the .NET 4.7.2 assemblies
since it was failing to resolve the OidGroup enum.

Mono.Cecil.ResolutionException: Failed to resolve
System.Security.Cryptography.OidGroup